# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

ARG VERSION

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies without running prepare scripts
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (not strictly required for stdio-based MCP)

# Set entrypoint to run the server
ENTRYPOINT ["node", "dist/index.js"]
